name: This is a github action
run-name: this is the run name
on: [push]
jobs: 
 Echo:
  runs-on: Ubuntu-latest
  steps: 
    - name: checkout repo
      uses: actions/checkout@v4
    - name: cat temp.txt
      run: cat temp.txt 
